// <auto-generated />
using FootballGamePlan.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballGamePlan.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("FootballGamePlan.Api.Models.GamePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GamePlans");
                });

            modelBuilder.Entity("FootballGamePlan.Api.Models.Play", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GamePlanId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPass")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GamePlanId");

                    b.ToTable("Plays");
                });

            modelBuilder.Entity("FootballGamePlan.Api.Models.PlayResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Coverage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamePlanId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPass")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassFailReason")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YardsGained")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GamePlanId");

                    b.HasIndex("PlayId");

                    b.ToTable("PlayResults");
                });

            modelBuilder.Entity("FootballGamePlan.Api.Models.Play", b =>
                {
                    b.HasOne("FootballGamePlan.Api.Models.GamePlan", null)
                        .WithMany("Plays")
                        .HasForeignKey("GamePlanId");
                });

            modelBuilder.Entity("FootballGamePlan.Api.Models.PlayResult", b =>
                {
                    b.HasOne("FootballGamePlan.Api.Models.GamePlan", "GamePlan")
                        .WithMany("Results")
                        .HasForeignKey("GamePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballGamePlan.Api.Models.Play", "Play")
                        .WithMany("Results")
                        .HasForeignKey("PlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GamePlan");

                    b.Navigation("Play");
                });

            modelBuilder.Entity("FootballGamePlan.Api.Models.GamePlan", b =>
                {
                    b.Navigation("Plays");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("FootballGamePlan.Api.Models.Play", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
